import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: "obsidian-copilot-agent",
	minify: prod,
});

import fs from "fs";
import path from "path";

function copyIfExists(sourcePath, destinationPath) {
	if (!fs.existsSync(sourcePath)) {
		return false;
	}

	const stat = fs.statSync(sourcePath);
	if (stat.isDirectory()) {
		fs.cpSync(sourcePath, destinationPath, { recursive: true });
	} else {
		fs.mkdirSync(path.dirname(destinationPath), { recursive: true });
		fs.copyFileSync(sourcePath, destinationPath);
	}

	return true;
}

if (prod) {
	await context.rebuild();

	// Copy manifest.json and styles.css to output directory
	const outputDir = "obsidian-copilot-agent";
	if (!fs.existsSync(outputDir)) {
		fs.mkdirSync(outputDir, { recursive: true });
	}

	// Copy manifest.json
	if (fs.existsSync("manifest.json")) {
		fs.copyFileSync("manifest.json", path.join(outputDir, "manifest.json"));
		console.log(`✓ Copied manifest.json to ${outputDir}/`);
	}

	// Copy styles.css
	if (fs.existsSync("styles.css")) {
		fs.copyFileSync("styles.css", path.join(outputDir, "styles.css"));
		console.log(`✓ Copied styles.css to ${outputDir}/`);
	}

	const bundledServerDir = path.join(
		"vendor",
		"copilot-runtime-sdk",
		"server-go",
	);
	if (copyIfExists(bundledServerDir, path.join(outputDir, "server-go"))) {
		console.log(
			`✓ Copied bundled remote server binaries to ${outputDir}/server-go/`,
		);
	}

	const vendorManifestPath = path.join(
		"vendor",
		"copilot-runtime-sdk",
		"manifest.json",
	);
	if (
		copyIfExists(
			vendorManifestPath,
			path.join(
				outputDir,
				"vendor",
				"copilot-runtime-sdk",
				"manifest.json",
			),
		)
	) {
		console.log(
			`✓ Copied remote SDK manifest to ${outputDir}/vendor/copilot-runtime-sdk/`,
		);
	}

	console.log(`✓ Build complete! Output in ${outputDir}/`);
	process.exit(0);
} else {
	await context.watch();
}
